crab submit -c Suu4TeV_chi500GeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu4TeV_chi850GeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu4TeV_chi1TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu4TeV_chi1p5TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu5TeV_chi1TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu5TeV_chi1p5TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu5TeV_chi2TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu6TeV_chi1TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu6TeV_chip5TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu6TeV_chi2TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu7TeV_chi1TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu7TeV_chi2TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu7TeV_chi3TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu8TeV_chi1TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
crab submit -c Suu8TeV_chi2TeV/CMSSW_10_6_20/src/crab_diquark_MINIAOD_prod_new_cfg.py
